### ISSUE TITLE
Embedded Presentation not working

### ISSUE THREAD

**Issue by rodrigopavezi** [Rise-Vision/viewer#271] opened 2017-07-31 13:59 UTC
Problem
Add your Display to this Schedule, https://apps.risevision.com/schedules/details/68bb90ab-ef74-4499-bfa9-3f3742e140c4?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

Embedded Presentations won't work.

However, I noticed our chrome player on uptime does play it and found it is using an older version of Viewer. 2-00-201609292007
https://apps.risevision.com/displays/details/XJZ58V3AMH9Y?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

v3 rise player doesn't play it all and is using Viewer 2-01-201707111735

We found out that if only happen when there is the same embedded presentation as part of the schedule. See below issue reported on console.

<img width="385" alt="screen shot 2017-07-28 at 17 33 57" src="https://user-images.githubusercontent.com/1659305/28781057-36d15442-75df-11e7-9312-ae11c2100ec4.png">

@ezequielc @fjvallarino @alex-deaconu could you please take a look at this issue?

cheers

**Comment by alex-deaconu** [comment] 2017-08-08 14:58
@rodrigopavezi the fix for this issue has been deployed. The cause was that the same Presentation object was used by the Schedule item and then copied and sent to the Embedded Presentation. The controllers modifies the HTML and causes a duplicate item to be added by the Embedded Presentation which causes the issue. To fix, I'm creating a separate copy of the object for the Schedule Item.

You can verify at: http://preview.risevision.com/?type=schedule&id=8fd59e2d-d8ae-40f4-8b23-ebc20f8c5f6c. 

Please verify and close if acceptable. Thanks!

**Comment by ezequielc** [comment] 2017-08-09 19:02
@rodrigopavezi @alex-deaconu I will close this as we fixed it. Feel free to reopen if needed. Thanks

**Closed by ezequielc** 2017-08-09 19:02 UTC
