### ISSUE TITLE
When in a schedule, Image Widget w/Fade transition does not obey Image order or schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/viewer#91] opened 2016-04-11 13:26 UTC
**How to recreate**
1. Within a presentation, add 2 Image Widgets 
2. Add Image #1 to first Image Widget, set it to display for 10 seconds
3. Add Image #2 to second Image Widget, set it to display for 10 seconds
4. Click Placeholder Properties and confirm that the default transition of Fade is enabled
5. Create a second presentation, add 2 Video Widgets
6. Add Video #1 to first Video Widget, set it to PUD
7. Add Video #2 to second Video Widget, set it to PUD
8. Add both presentations to a schedule, set each presentation to PUD
9. Run schedule on a display

**What happens**
Presentation #1 shows its first image for 10 secs, fades out and fades in second image and displays 10 secs. Then the presentation #2 is immediately shown without fading out that second image.

When presentation #2 completes, it switches back to presentation #1  and that last Image previously shown is still appearing and is immediately faded out and fades in the first one.

**What should happen**
Each iteration of the Image Widget should begin at 0 seconds on Image #1, run for 10 seconds, continue to Image #2, run for 10 seconds, then continue on to anything left in the schedule. Images should not briefly show on screen when the Image Widget starts.

**Notes**
OS Windows 10
Chrome ver 49.*
I also tested this using the Image as Folder, and unchecking "Resume playing from last position". I saw the same defect.

**Presentation**
https://apps.risevision.com/editor/workspace/ed7dc1ad-eb90-44f2-87cf-435192a07980/?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

**Schedule**
https://apps.risevision.com/schedules/details/1f3f9bc7-6cf2-4504-9159-c1db789532d3?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

**Comment by alex-deaconu** [comment] 2016-04-29 19:07
Confirmed issues exist, however, works as designed. Since the viewer is going to be deprecated, the decision has been made to not fix this in this repository.

Closing. @ByronDarlison @btfrise FYI.

Thanks!

**Closed by alex-deaconu** 2016-04-29 19:07 UTC
Labels: bug

**Comment by dalebradshaw** [comment] 2016-05-23 21:48
Hi, 
I'm having the above problem. Which widget or technique should I be using since this won't be fixed?

**Comment by robb-price** [comment] 2016-05-24 14:54
@dalebradshaw Can I ask you to email support@risevision.com with a link to your Presentation so we can investigate if there is a better way to achieve what you need?

Thanks!

**Comment by hcs0** [comment] 2016-05-31 15:26
To update, the above issue with dalebradshaw's presentations has been resolved (it was another type of issue).  Thanks!
